<?php if (!isset($_SESSION)) {session_start();}

echo '<h4>Resumen del historico del stock y usos de feretros.</h4>';
echo '<table>';
	echo '<tr>';				
		echo '<td>';
			echo "Cantidad total producida hasta hoy";
		echo '</td>';
		echo '<td class="derecha" colspan="2">';
			echo '&nbsp&nbsp&nbsp&nbsp';
			echo number_format($total_general,0,",",".");
		echo '</td>';
	echo '</tr>';
	echo '<tr>';				
		echo '<td>';
			echo "Cantidad total dada de baja por mal estado";
		echo '</td>';
		echo '<td class="derecha" colspan="2">';
			echo '&nbsp&nbsp&nbsp&nbsp';
			echo number_format($total_mal_estado,0,",",".");
		echo '</td>';
	echo '</tr>';
	echo '<tr>';				
		echo '<td>';
			echo "Cantidad total utilizada para dar garantia";
		echo '</td>';
		echo '<td class="derecha" colspan="2">';
			echo '&nbsp&nbsp&nbsp&nbsp';
			echo number_format($total_garantia,0,",",".");
		echo '</td>';
	echo '</tr>';				
	echo '<tr>';				
		echo '<td colspan="3">';
			echo '<hr/>';
		echo '</td>';
	echo '</tr>';					
	echo '<tr>';
		echo '<td>';
			echo "Saldo Operacional";
		echo '</td>';
		echo '<td class="derecha">';
			$saldo_1 = $total_general - $total_mal_estado - $total_garantia;
			echo number_format($saldo_1,0,",",".");
		echo '</td>';
	echo '</tr>';					
	echo '<tr>';				
		echo '<td colspan="3">';
			echo '<hr/>';
		echo '</td>';
	echo '</tr>';					
	echo '<tr>';				
		echo '<td>';
			echo "Cantidad total utilizados en servicios";
		echo '</td>';
		echo '<td class="derecha" colspan="2">';
			echo '&nbsp&nbsp&nbsp&nbsp';
			echo number_format($total_utilizados,0,",",".");
		echo '</td>';
	echo '</tr>';				
	echo '<tr>';				
		echo '<td>';
			echo "Cantidad total de crudos en stock actual";
		echo '</td>';
		echo '<td class="derecha" colspan="2">';
			echo '&nbsp&nbsp&nbsp&nbsp';
			echo number_format($total_crudos,0,",",".");
		echo '</td>';
	echo '</tr>';				
	echo '<tr>';				
		echo '<td>';
			echo "Cantidad total de terminados en stock actual";
		echo '</td>';
		echo '<td class="derecha" colspan="2">';
			echo '&nbsp&nbsp&nbsp&nbsp';
			echo number_format($total_terminados,0,",",".");
		echo '</td>';
	echo '</tr>';
	echo '<tr>';				
		echo '<td colspan="3">';
			echo '<hr/>';
		echo '</td>';
	echo '</tr>';					
	echo '<tr>';				
		echo '<td>';
			echo "Variacion o casos sin status determinado";
		echo '</td>';
		echo '<td class="derecha" colspan="2">';
			echo '&nbsp&nbsp&nbsp&nbsp';
			$saldo_2 = $saldo_1 - $total_utilizados - $total_crudos - $total_terminados;
			echo '<span class="rojo">'.number_format($saldo_2,0,",",".").'</span>';
		echo '</td>';
	echo '</tr>';
	echo '<tr>';				
		echo '<td colspan="3">';
			echo '<hr/>';
		echo '</td>';
	echo '</tr>';									
echo '</table>';

?>
